# GraphQL schema example
#
# https://gqlgen.com/getting-started/

type Todo {
  id: ID!
  text: String!
  done: Boolean!
  user: User!
}

type User {
  id: ID!
  name: String!
  pictureUrl: String
}

# type Ingredient {
#   item: String
#   amount: String
# }

# type Ingredients {
#   servings: String
#   list: [Ingredient]
# }

# type BreadcrumbItem {
#   name: String
#   href: String
# }

type Video {
  thumbnailUrl: String
  source: String
  type: String
}

# type Step {
#   description: String
# }

# type Taberepo {
#   user: User
#   stars: Float
#   comment: String
#   date: String
#   pictureUrl: String
# }

# type TaberepoListing {
#   stars: Float
#   numReviews: Int
#   numReports: Int
#   list: [Taberepo]
# }

type Recipe {
  id: ID
  # title: String
  # subTitle: String
  # introduction: String
  ###############################
  # cookingTime: String
  # expense: String
  # ingredients: Ingredients
  # breadcrumbs: [BreadcrumbItem]
  video: Video
  # steps: [Step]
  # tips: String
  # taberepo: TaberepoListing
}

type Query {
  todos: [Todo!]!
  recipe(id: ID): Recipe
}

input NewTodo {
  text: String!
  userId: String!
}

type Mutation {
  createTodo(input: NewTodo!): Todo!
}
