// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Ingredient struct {
	Item   *string `json:"item"`
	Amount *string `json:"amount"`
}

type Ingredients struct {
	Servings *string       `json:"servings"`
	List     []*Ingredient `json:"list"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Recipe struct {
	ID          *string      `json:"id"`
	Ingredients *Ingredients `json:"ingredients"`
	Video       *Video       `json:"video"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID         string  `json:"id"`
	Name       string  `json:"name"`
	PictureURL *string `json:"pictureUrl"`
}

type Video struct {
	ThumbnailURL *string `json:"thumbnailUrl"`
	Source       *string `json:"source"`
	Type         *string `json:"type"`
}
